# cpanel.yml

# Define the deployment environment
environments:
  production:
    branches:
      - main

# Specify deployment strategy
deployment_strategy:
  production:
    provider: cpanel
    cpanel:
      cpanel_domain: "aidenauria.my.id" # Replace with your actual domain
      cpanel_username: "kjbvdoiy" # Replace with your cPanel username
      cpanel_password: "Blank991202" # Replace with your cPanel password

# Specify deployment steps
steps:
  - name: Install Composer Dependencies
    command: composer install --optimize-autoloader --no-dev

  - name: Set Laravel Environment
    command: cp .env.example .env

  - name: Generate Laravel Application Key
    command: php artisan key:generate

  - name: Migrate Database
    command: php artisan migrate --force

  - name: Optimize Laravel
    command: php artisan optimize

  - name: Create Symbolic Link to Storage
    command: php artisan storage:link

# Optional: Add any additional steps or configurations specific to your application

# Specify any post-deployment steps
post_deployment:
  - name: Clear Application Cache
    command: php artisan cache:clear

  - name: Clear Configuration Cache
    command: php artisan config:cache

  - name: Clear Route Cache
    command: php artisan route:cache

# Specify any specific considerations for shared hosting, such as database setup
shared_hosting:
  database:
    database_name: "kjbvdoiy_sippdb" # Replace with your desired database name
    database_username: "kjbvdoiy_admin " # Replace with your desired database username
    database_password: "Blank991202" # Replace with your desired database password

# Optional: Add any other configurations or considerations for shared hosting

# Specify cleanup steps
# cleanup:
#   - name: Remove Unnecessary Files
#     command: rm -rf node_modules public/build

# Specify rollback steps
# rollback:
#   - name: Rollback Database Migrations
#     command: php artisan migrate:rollback --force

# Specify any other deployment-related configurations
# ...
